import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import AuthProvider from "./session-provider";
import { Theme } from "@radix-ui/themes";
import NavBar from "./components/NavBar";
import { ToastContainer } from "react-toastify"
import "react-toastify/dist/ReactToastify.css"
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <AuthProvider>
          <Theme appearance="dark">
            <NavBar />
            {children}
            <ToastContainer
              position="bottom-right"
              autoClose={3000}
              hideProgressBar={false}
              newestOnTop
              closeOnClick
              rtl={false}
              pauseOnFocusLoss
              draggable
              pauseOnHover
              theme="light"
            />
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
